EVALUATE
TOPN (
    10,
    SUMMARIZECOLUMNS (
        gold_cost_by_resource[ServiceName],
        FILTER ( ALL ( gold_cost_by_resource[ServiceCategory] ), gold_cost_by_resource[ServiceCategory] = "Analytics" ),
        FILTER ( ALL ( gold_cost_by_resource[YearMonth] ), gold_cost_by_resource[YearMonth] IN { "2026-05", "2026-06" } ),
        "Cost", [Resource Effective Cost]
    ),
    [Cost], DESC
)
ORDER BY [Cost] DESC
